version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy:
    machine:
      enabled: true

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - '3e:ee:bc:8e:1d:bc:1c:19:fa:d6:7d:90:89:96:34:ee'
      - checkout
      - run:
          name: Push Master to Production
          command: |
            git push https://github.com/lighthouse-labs/scheduler.git master:production

  workflows:
    version: 2
    test_and_deploy:
      jobs:
        - build:
            filters:
              branches:
                ignore: production
        - deploy:
            filters:
              branches:
                ignore: production
            requires:
              - build
