export const SET_DAY = 'SET_DAY';
export const SET_APPLICATION_DATA = 'SET_APPLICATION_DATA';
export const SET_INTERVIEW = 'SET_INTERVIEW';
export const CANCEL_INTERVIEW = 'CANCEL_INTERVIEW';
export const UPDATE_SPOTS = 'UPDATE_SPOTS';
